### ISSUE TITLE
Error in log too many requests

### ISSUE THREAD

**Issue by JoshuaShelswell** [jesmak/MMM-FlightRadarTracker#6]
maybe make the request amount less?

[2020-12-18 18:58:06.910] [ERROR]  Error: Too Many Requests
    at /home/pi/MagicMirror/modules/MMM-FlightRadarTracker/node_modules/flightradar24-client/lib/flight.js:26:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  statusCode: 429
}
[2020-12-18 19:01:46.282] [ERROR]  Error
    at /home/pi/MagicMirror/modules/MMM-FlightRadarTracker/node_modules/flightradar24-client/lib/flight.js:26:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  statusCode: 520
}
[2020-12-18 19:01:46.315] [ERROR]  Error
    at /home/pi/MagicMirror/modules/MMM-FlightRadarTracker/node_modules/flightradar24-client/lib/flight.js:26:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  statusCode: 520
}
[2020-12-18 19:01:46.786] [ERROR]  Error
    at /home/pi/MagicMirror/modules/MMM-FlightRadarTracker/node_modules/flightradar24-client/lib/flight.js:26:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  statusCode: 520
}
[2020-12-18 19:01:47.123] [ERROR]  Error
    at /home/pi/MagicMirror/modules/MMM-FlightRadarTracker/node_modules/flightradar24-client/lib/flight.js:26:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  statusCode: 520
}

**Comment by jesmak** [comment]
What is your update interval and limit for shown flights? If update interval is too quick and there's lots of flights to show, this will happen.

**Comment by JoshuaShelswell** [comment]
i put it to 3000 not sure if lower is better but i figured higher number the more infrequent the interval

        {
            module: 'MMM-FlightRadarTracker',
            header: 'Nearby planes',
            position: 'bottom_left',
            config: {
                updateInterval: 3000,
                distance: 60,
                passingByThreshold: -1,
                limit: 2,
                speedUnits: 'imperial',
                altitudeUnits: 'imperial',
                centerPoint: [35.202099, -81.135597],
                showAirline: true,
                showType: true,
                showSpeed: true,
                showAltitude: true,
                showHeading: true,
                showDirectionAsArrow: true,
                showRoute: true,
                noPlanesLabel: 'No Planes Nearby',
                atTheWindowLabel: 'At The Window',
                passingByLabel: 'Passing By',
		sort: 'distance|speed|altitude|flight|airline',
		sortDescending: false,
			}
        },

**Comment by matze6486** [comment]
@ghost

I've got the same issue and tried different updateIntervalls: 1, 5, 10, 50, 100, 500, 1000. But always the same error in the terminal

Did you have solved your problem yet?
