### ISSUE TITLE
Cannot find module 'flightradar24-client/lib/radar

### ISSUE THREAD

**Issue by BurgerhoutJ** [jesmak/MMM-FlightRadarTracker#8]
I'm running Magic Mirror in Docker and installed the MMM-FlightRadarTracker, but when I want to start the Docker image, then I receive the following errors:

```
[12.02.2021 15:36.45.900] [ERROR] Whoops! There was an uncaught exception...
[12.02.2021 15:36.45.905] [ERROR] Error: Cannot find module 'flightradar24-client/lib/radar'
Require stack:
- /opt/magic_mirror/modules/MMM-FlightRadarTracker/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/serveronly/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-FlightRadarTracker/node_helper.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/magic_mirror/modules/MMM-FlightRadarTracker/node_helper.js',
    '/opt/magic_mirror/js/app.js',
    '/opt/magic_mirror/serveronly/index.js'
  ]
```

So far as I can read this, then the module wants to access the flightradar24 module. But I haven't installed this.
What can I do to resolve this?

**Comment by BurgerhoutJ** [comment]
not necessary anymore
